version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    environment:
      SECRET_KEY: yoursecretkey
      DATABASE_URL: postgresql://user:password@db:5432/mydb
      MAIL_SERVER: smtp.example.com
      MAIL_PORT: '587'
      MAIL_USERNAME: your_smtp_username
      MAIL_PASSWORD: your_smtp_password
    depends_on:
      - db
    restart: always

  nginx:
    image: nginx:alpine
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    restart: always

volumes:
  db_data: